name: Build and Publish Generated Files

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests lxml

    - name: Run scripts to generate files
      run: |
        python scripts/ChinaIP.py
        python scripts/ChinaASN.py
        python scripts/ChinaROS.py

    - name: Push generated files to release-files branch
      run: |
        mkdir generated
        mv *.rsc *.list generated/ || true

        cd generated
        git init
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update generated files"
        git branch -M release-files
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push --force origin release-files